/*
CREATE TABLE Account (
    IdCuenta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NumeroCuenta VARCHAR(25) NOT NULL,
    FechaObertura DATE,
    Saldo DECIMAL(19,4)
);
 */

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

public class Account {

    private int idAccount;
    private String accountNumber;
    private LocalDate openingDate;
    private float balance;
    private static int idCount = 1;

    public Account(String accountNumber, LocalDate openingDate, float balance){
        this.idAccount = idCount;
        this.accountNumber = accountNumber;
        this.openingDate= openingDate;
        this.balance= balance;
        idCount++;
    }
    public Account(String accountNumber){
        this.idAccount = idCount;
        this.accountNumber = accountNumber;
        this.openingDate= LocalDate.now();
        this.balance= 0.0f;
        idCount++;
    }

    /*
    public void setIdAccount(int idAccount){
        this.idAccount = idAccount;
    }
     */
    public void setAccountNumber(String accountNumber){
        this.accountNumber = accountNumber;
    }
    public void setOpeningDate(LocalDate openingDate){
        this.openingDate = openingDate;
    }
    public void setBalance(float balance){
        this.balance = balance;
    }

    public int getIdAccount(){
        return idAccount;
    }
    public String getAccountNumber(){
        return accountNumber;
    }
    public LocalDate getOpeningDate(){
        return openingDate;
    }
    public float getBalance(){
        return balance;
    }
    public static int getNumberOfAccounts(){
        return idCount-1;
    }

    public void accountInfo(){
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d 'de' MMMM 'de' yyyy", new Locale("es", "ES"));
        String formattedDate = openingDate.format(formatter);
        System.out.println("The account number " + accountNumber + "\nwas opened on " + openingDate +
                "\nwith the ammount of " + balance + "Eu. The id is: " + idAccount);
    }

}
